name: GitHub Pages

on:
  push:
    branches:
      - main  # 替换为你的默认分支名称

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # 如果使用了子模块主题，保留此选项
          fetch-depth: 0    # 拉取所有历史，用于正确生成时间戳

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # 选择合适的 Node.js 版本

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install  # 安装 package.json 中的所有依赖，包括主题

      - name: Build
        run: npm run build  # 执行 Hexo 构建命令

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Hexo 默认生成的静态文件目录